### ISSUE TITLE
NPC-192 tooltip contains false information.

### ISSUE THREAD

**Issue by Alucard648** [Wohlstand/TheXTech-SDK#1]
**Describe the issue**
![false1](https://user-images.githubusercontent.com/7596025/188270829-98cc57b9-4a1c-4b84-98a3-b771aec55f68.png)

Warning written in bold at the bottom, as of latest version of X-Tech, is false. Multipoints tested and fully functional.

**Comment by Wohlstand** [comment]
Forgot to close this, I fixed this a while ago.
